### ISSUE TITLE
Stop updating unversioned release JS file

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#16]
Spec drafts like https://raw.githack.com/oasis-tcs/oslc-domains/master/qm/quality-management-vocab.html and https://tools.oasis-open.org/version-control/svn/oslc-promcode/shape/trunk/spec.html directly reference https://ndjc.github.io/respec/builds/oasis/respec-oasis-common.js. We should also probably revert that file to pre-OP version.

**Comment by berezovskyi** [comment]
@ndjc I suggest to revert respec-oasis-common.js to https://github.com/oasis-tcs/tab-respec/commit/cf40b85a9dd8251b3eea8c0adac0f7c69c008204 (last commit before https://github.com/oasis-tcs/tab-respec/commit/756b7ad89b9e39218475cdff402046e012b2c33d)

**Comment by ndjc** [comment]
The ReSpec at https://ndjc.github.io/respec/builds/oasis/respec-oasis-common.js is pre-OP; it is part of an archived GitHub project, and was version 1.0.1.
I don't agree with changing the unversioned release of the current oasis-tcs/tab-respec repo to be fixed at some specific past commit. I would want any draft spec (such as config management, trs, etc.) to use the latest build. Once a spec is mature enough to want a fixed version of ReSpec, it can change to do so.

**Comment by berezovskyi** [comment]
Right! It’s a different repo, I totally missed it! Please close.

--
/Andrew
(from phone)

18 sep. 2019 kl. 16:14 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


The ReSpec at https://ndjc.github.io/respec/builds/oasis/respec-oasis-common.js is pre-OP; it is part of an archived GitHub project, and was version 1.0.1.
I don't agree with changing the unversioned release of the current oasis-tcs/tab-respec repo to be fixed at some specific past commit. I would want any draft spec (such as config management, trs, etc.) to use the latest build. Once a spec is mature enough to want a fixed version of ReSpec, it can change to do so.
