### ISSUE TITLE
master branch is protected

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#2]
@ndjc was complaining that PRs are a "pain in the neck" for repos like this with low committer activity. @chet-ensign, could you please accommodate his request and unprotect the master branch, please?

**Comment by berezovskyi** [comment]
cc @jamsden

**Comment by OASIS-OP-Admin** [comment]
I just checked the settings and I don't see any branch protection rules in place. @ndjc should be able to directly commit to the repo. Let me know if that's not the case.

**Comment by berezovskyi** [comment]
My bad. I tried editing the README file through the web interface to test if the branch is protected and missed. Thanks a lot for checking!
