### ISSUE TITLE
Pin last good version pre-OP

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#33]

**Comment by ndjc** [comment]
There is no version of ReSpec in this repo that is pre-OP. The first version committed here had significant changes for OP.

We could create an entirely new branch that was a copy of the TC version of ReSpec at  https://ndjc.github.io/respec/builds/oasis/respec-oasis-common.js, or I could try to make the change at the older location - however, that project has been archived, and has no long-term future.
