### ISSUE TITLE
Backport specref fix

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#34]
Backport #30 on the branch off #33

**Comment by ndjc** [comment]
I have now created the branch [tc-branch](/oasis-tcs/tab-respec/tree/tc-branch).

**Comment by berezovskyi** [comment]
https://cdn.jsdelivr.net/gh/oasis-tcs/tab-respec@tc-v1.0.2/builds/oasis/respec-oasis-common.min.js  published
