### ISSUE TITLE
year and publisher in the list of references

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#46]
**Is your feature request related to a problem? Please describe.**
From an academic pov, I think the year and publisher are essential elements of a citation.

**Describe the solution you'd like**
- _year_ key shall be added to the JSON object for each reference
- _publisher_ key shall be used in the rendering

**Describe alternatives you've considered**
We can stuff the _status_ key but I would rather we not do this.

**Additional context**

![image](https://user-images.githubusercontent.com/64734/106895920-2216c080-66f1-11eb-902c-95ae1bf6110d.png)

**Comment by ndjc** [comment]
Added a bug fix required by TRS 3.0.
@berezovskyi  - please review so we can pull the biblio change and the bug fix into master.
