### ISSUE TITLE
Multiple clauses have no separation

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#47]
Here is the original:

![image](https://user-images.githubusercontent.com/64734/107273227-0db72880-6a4f-11eb-9a30-065380e4c0e4.png)

First attempt at fixing it:

![image](https://user-images.githubusercontent.com/64734/107273559-81593580-6a4f-11eb-9faf-c78e204e95e1.png)

**Comment by berezovskyi** [comment]
For now, I am working around this with newlines:

![image](https://user-images.githubusercontent.com/64734/107273893-fa588d00-6a4f-11eb-97bb-06170f1ded4c.png)

**Comment by berezovskyi** [comment]
cc @ndjc @jamsden

**Comment by ndjc** [comment]
I believe this is working as designed. If you want conformance clauses separated, you should separate them in the source using multiple paragraphs or similar HTML formatting - I do not believe it is ReSpec's job to invent formatting for you - whatever it invents might be wrong in some circumstance.
