### ISSUE TITLE
dcterms:issued and dt-published do not match

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#54]
**Describe the bug**
When the spec snapshot is saved, the dcterms:issued and dt-published are added but they do not match. From https://issues.oasis-open.org/browse/TCADMIN-3996:

`<span property="dcterms:issued" datatype="xsd:dateTime" content="2021-05-26T22:00:00.000Z"><time class="dt-published" datetime="2021-05-27">27 May 2021</time></span>`

**To Reproduce**
1. Go to CM OS spec
1. Save Snapshot
1. See error in the source code.

**Expected behavior**
The dates in both properties shall match.

**ReSpec version**
v2.1.25

**Comment by berezovskyi** [comment]
@ndjc could you please give me a hand here? Any ideas where we should start looking? Is this a behaviour we altered or do we suspect a bug in the W3C version of ReSpec?

**Comment by paul-knight** [comment]
It is possible that some timezone effect is involved:
- i.e., the time "2021-05-26T22:00:00.000Z" may be already 27 May for a system located two or more timezones later (East)
- (possibly helpful hint) In timestamping publications in OASIS Library, we assign the time to be 12:00Z to minimize this effect.

**Comment by berezovskyi** [comment]
Just confirmed it, you are right @paul-knight! Z is a timezone Zulu aka UTC, I am in +0200, and 00:00+0200 can become 22:00Z:

![image](https://user-images.githubusercontent.com/64734/120847638-0e327c80-c574-11eb-91bb-e19038862443.png)

@ndjc we need to update the `parseSimpleDate` in the utils.js to simply parse the string instead of doing substring magic:

![image](https://user-images.githubusercontent.com/64734/120847514-e04d3800-c573-11eb-8339-445d18e047c3.png)

![image](https://user-images.githubusercontent.com/64734/120847558-f2c77180-c573-11eb-89a2-74a523228896.png)
