### ISSUE TITLE
ReSpec renders publishDate one day earlier than specified

### ISSUE THREAD

**Issue by jamsden** [oasis-tcs/tab-respec#57]
**Describe the bug**
tracked-resource-set.html specifies publishDate as ` publishDate: "2021-08-05",` but when ReSpec renders the HTMl source, it displays 04 August 2021. 

**To Reproduce**
1. Open tracked-resource-set.html 
2. See the rendered publish date is 04 August 2021
3. Open the html source.
4. See ` publishDate: "2021-08-05",`

**Expected behavior**
Date should display as 05 August 2021 as specified for the publishDate.

**ReSpec version**
2.1.27

**Comment by berezovskyi** [comment]
That’s a regression, will look into that. Most likely related to my recent fix where rdf metadata date lagged one day due to a timezone difference.

–Andrew

**Comment by paul-knight** [comment]
This is almost certainly a time zone issue.
I think it sets the time to 00:00:01 or similar by default.
The simplest way to handle it is to set the time in addition to the date.
In the OASIS publications (OASIS Library), we set the timestamp using Noon UTC, so it will likely be translated by most computer systems as being the expected date.

**Comment by berezovskyi** [comment]
The regression is fixed. Thanks for the suggestion, Paul, I added the 12:00Z timestamp value as a checklist item to the wiki: https://github.com/oslc-op/oslc-specs/wiki/EPIC-checklist#spec-text-and-respec
